---
surls: 
  - "redis://:redistest0102@114.67.76.82:16377/"
turls:
  - "redis://:redistest0102@114.67.76.82:16377/"
batch_size: 10
threads: 2
ttl_diff: 10
compare_times: 1
compare_interval: 1
report: false
scenario: Single2single 
