---
source:
  - instance:
      urls:
        - "redis://:password_source_1@127.0.0.1:6379/?timeout=1s"
      password: ""
      instance_type: single
    dbmapper:
      4: 4
      0: 1
      3: 5
  - instance:
      urls:
        - "redis://:password_source_2@127.0.0.1:6380/?timeout=1s"
      password: ""
      instance_type: single
    dbmapper:
      4: 3
      2: 5
      0: 1
  - instance:
      urls:
        - "redis://127.0.0.1:26379"
        - "redis://127.0.0.1:26380"
        - "redis://127.0.0.1:26381"
      password: xxxx
      instance_type: cluster
    dbmapper:
      0: 1
target:
  urls:
    - "redis://:password_target@127.0.0.1:6382/?timeout=1s"
  password: ""
  instance_type: single
batch_size: 10
threads: 1
compare_threads: 1
ttl_diff: 1
compare_times: 1
compare_interval: 1
report: false
scenario: multisingle2single
bothway: false
