---
source:
  - instance:
      urls:
         - "redis://:redistest0102@114.67.76.82:16377"
      password: ""
    dbmapper:
      0: 0 
target:
  urls:
    - "redis://:redistest0102@114.67.76.82:16377/"
  password: ""
batch_size: 10
threads: 1
compare_threads: 1
ttl_diff: 1
compare_times: 1
compare_interval: 1
report: false
scenario: multisingle2single
bothway: true
